"""Report rendering: Markdown and PDF exports of the evidence-backed investigation report.

Both renderers work purely from the stored `final_report` document (no LLM calls), so an
export is always identical to what the analyst saw in the UI.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

SECTION_TITLES = {
    "1_incident_title": "Incident title", "2_alert_summary": "Alert summary", "3_severity": "Severity assessment",
    "4_affected_entities": "Affected entities", "5_source_destination": "Source / destination analysis", "6_attack_timeline": "Attack timeline",
    "7_attack_chain": "Attack chain reconstruction", "8_knowledge_graph_summary": "Knowledge graph summary", "9_behavioral_evidence": "Behavioral evidence",
    "10_threat_intelligence": "Threat intelligence", "11_mitre_mapping": "MITRE ATT&CK mapping", "12_supporting_evidence": "Supporting evidence",
    "13_ai_attack_narrative": "AI attack narrative", "14_recommended_actions": "Recommended actions", "15_investigation_limitations": "Investigation limitations",
}


def _fmt(v: Any) -> str:
    if v is None:
        return "—"
    if isinstance(v, (list, dict)):
        return "```json\n" + json.dumps(v, indent=1, default=str)[:6000] + "\n```"
    return str(v)


def report_to_markdown(report: Dict[str, Any]) -> str:
    s = report.get("sections", {})
    out: List[str] = []
    out.append(f"# {s.get('1_incident_title', 'Investigation report')}")
    out.append(f"*Investigation `{report.get('investigation_id')}` · alert `{report.get('alert_id')}` · generated {report.get('generated_at')}*")
    prov = report.get("provenance") or {}
    if prov:
        out.append(f"> **Provenance:** {prov.get('banner') or json.dumps(prov, default=str)}")
    sev = s.get("3_severity", {})
    out.append(f"\n## Severity: **{str(sev.get('level', '')).upper()}**")
    for r in sev.get("rationale", []):
        out.append(f"- {r}")
    out.append("\n## Alert summary")
    for k, v in (s.get("2_alert_summary") or {}).items():
        out.append(f"- **{k}**: {v}")
    out.append("\n## Analyst summary")
    out.append(str(report.get("analyst_summary") or "—"))
    out.append("\n## Attack chain")
    chain = s.get("7_attack_chain", {})
    for st in chain.get("stages", []):
        out.append(f"{st['stage']}. **{st['attack_type']}** ({st.get('category')}) — {st.get('event_count')} flows, {st.get('first_seen')} → {st.get('last_seen')}; "
                   f"sources {', '.join(st.get('sources', []))}; targets {', '.join(st.get('targets', []))}; support: {st.get('support')}; evidence: {', '.join(st.get('evidence_ids', [])[:5])}")
    for r in chain.get("relationships", []):
        timing = (f"overlapping by {r.get('overlap_seconds', 0):.0f} s" if r.get("temporal_relation") == "overlapping"
                  else f"gap {r.get('gap_seconds')} s")
        out.append(f"   - stage {r['from_stage']} → {r['to_stage']}: {r['link_strength']} link, {timing}, shared targets {', '.join(r.get('shared_targets', [])) or 'none'}")
    out.append(f"\n*Method:* {chain.get('method')}")
    sd = s.get("5_source_destination", {})
    if sd.get("distributed_sources"):
        out.append("\n## Distributed sources (same target, same window)")
        for d in sd["distributed_sources"]:
            out.append(f"- {d['source_ip']}: {', '.join(sorted(set(d['attack_types'])))} — {d['event_count']} flows [{', '.join(d['evidence_ids'][:3])}]")
    if sd.get("other_activity_on_targets"):
        out.append("\n## Other activity observed on the same targets (context only)")
        for o in sd["other_activity_on_targets"]:
            out.append(f"- {o['attack_type']} from {', '.join(o['sources'])} — {o['event_count']} flows, {o['first_seen']} → {o['last_seen']}")
    out.append("\n## Evidence-backed claims")
    for c in report.get("claims", []):
        out.append(f"- {'✅' if c.get('validated') else '⚠️'} {c['text']}  \n  evidence: {', '.join(c.get('evidence_ids', [])[:6]) or 'none'}")
    out.append("\n## AI attack narrative")
    narr = s.get("13_ai_attack_narrative", {})
    out.append(f"*Generated by: {narr.get('generated_by')} · model: {narr.get('model') or 'n/a'} · grounding validation: {json.dumps(narr.get('grounding_validation'), default=str)}*\n")
    out.append(str(narr.get("text", "")))
    out.append("\n## Threat intelligence (actual API results)")
    ti = s.get("10_threat_intelligence", {})
    if not ti.get("results"):
        out.append("Insufficient evidence — no external reputation data obtained.")
    for r in ti.get("results", []):
        out.append(f"- **{r.get('provider')}** {r.get('indicator')}: status `{r.get('status')}` verdict `{(r.get('normalized') or {}).get('verdict')}` — {r.get('note') or ''}")
    out.append("\n## MITRE ATT&CK mapping")
    for m in s.get("11_mitre_mapping", []):
        out.append(f"- {m['attack_type']} ↔ **{m['technique_id']}** {m['name']} ({m.get('tactic')}; confidence {m.get('confidence')}; bundle-verified: {m.get('verified_against_bundle')})  \n  {m.get('rationale')}")
    out.append("\n## Behavioral evidence")
    be = s.get("9_behavioral_evidence", {})
    for f in be.get("top_features", [])[:8]:
        out.append(f"- {f['feature']}: z vs benign = {f.get('z_vs_benign')}")
    out.append("\n## Supporting evidence items")
    for e in s.get("12_supporting_evidence", []):
        out.append(f"- `{e['evidence_id']}` step {e['step']} **{e['tool']}** → {e['summary']} (records {e.get('record_count')}/{e.get('total_matched')}{', truncated' if e.get('truncated') else ''})")
    out.append("\n## Knowledge graph summary")
    out.append(_fmt(s.get("8_knowledge_graph_summary")))
    out.append("\n## Recommended actions")
    for a in s.get("14_recommended_actions", []):
        out.append(f"- {a}")
    out.append("\n## Investigation limitations")
    for l in s.get("15_investigation_limitations", []):
        out.append(f"- {l}")
    m = report.get("metrics", {})
    out.append("\n## Investigation metrics")
    out.append(_fmt(m))
    return "\n".join(out)


def report_to_pdf(report: Dict[str, Any], path: Path) -> Path:
    """Simple ReportLab rendering of the Markdown view (headings + paragraphs)."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    from xml.sax.saxutils import escape

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(str(path), pagesize=A4, leftMargin=1.6 * cm, rightMargin=1.6 * cm, topMargin=1.5 * cm, bottomMargin=1.5 * cm)
    flow = []
    md = report_to_markdown(report)
    in_code = False
    code_buf: List[str] = []
    for line in md.splitlines():
        if line.startswith("```"):
            if in_code:
                flow.append(Paragraph("<font face='Courier' size='7'>" + escape("\n".join(code_buf)).replace("\n", "<br/>").replace(" ", "&nbsp;") + "</font>", styles["Normal"]))
                code_buf = []
            in_code = not in_code
            continue
        if in_code:
            code_buf.append(line[:160])
            continue
        if not line.strip():
            flow.append(Spacer(1, 4))
            continue
        text = escape(line)
        text = text.replace("**", "")
        if line.startswith("# "):
            flow.append(Paragraph(text[2:], styles["Title"]))
        elif line.startswith("## "):
            flow.append(Paragraph(text[3:], styles["Heading2"]))
        elif line.startswith("> "):
            flow.append(Paragraph("<i>" + text[2:] + "</i>", styles["Normal"]))
        elif line.startswith("- ") or line.startswith("   - "):
            flow.append(Paragraph("• " + text.lstrip(" -"), styles["Normal"]))
        else:
            flow.append(Paragraph(text, styles["Normal"]))
    doc.build(flow)
    return path
